### ISSUE TITLE
Alternate characters

### ISSUE THREAD

**Issue by jackbond** [coenm/Z85e#7]
Hi,

I've been experimenting with your code to see if I could get a slightly modified version working. The project I'm working on sends z85 encoded strings over SMS, but it appears some of our messages are getting modified en route. This document outlines which characters are compatible with SMS, https://en.wikipedia.org/wiki/GSM_03.38, which leads me to believe that the Z85 characters ^ [ ] { } are not 100% safe. I tried replacing them with £ ¥ æ ß § in Map.Encoder, but it didn't work. My guess is that Decoder would likewise need to be modified, but it wasn't clear to me how that array was calculated. Any chance you provide some guidance? Thanks.

**Comment by coenm** [comment]
Hi,

I don't know anything about SMS specs etc. You could manually try to text someone with the (possible) illegal sms characters ( ^ [ ] { } ) to be sure.

Probably later this week I can find some time to explain the decoding.

In the mean time you could read this https://en.wikipedia.org/wiki/Ascii85 article. It explains how the base85 encoding works.

**Comment by jackbond** [comment]
I plunged a bit deeper into your code, and managed to replace the Map.Decoder array with this...

`internal static readonly Dictionary<char, byte> DecodingDictionary = Encoder.Select((val, index) => new { val, index }).ToDictionary(z => z.val, z => (byte)z.index);`

Then anywhere with a reference like this...

`z85Decoder[(byte)src[charNbr + 1]];`

I replaced with 

`Map.DecodingDictionary[src[charNbr + 1]];`

The performance was just about identical without resorting to pointers. The other benefit was that you can freely replace characters in Map.Encoder with characters that have ASCII values higher than 127. Obviously the resulting strings will no longer be Z85, but that's what I needed.

**Comment by coenm** [comment]
@jackbond 
Sorry, I wasn't able to take a look and to explain earlier. Glad you found how it works and how to solve your problem. Let me know if you have any questions left. If I can find the time, I'm willing to help.
